<?php //@todo: remove the file as below is not in use
$order = new Mage_Sales_Model_Order();
$orderId = Mage::getSingleton('checkout/session')->getLastRealOrderId();
$order->loadByIncrementId($orderId);
?>
<h2><?php echo $this->__('Unipagos Payment') ?></h2>
<form name="wallet" method="post" action="<?php echo Mage::helper('wallet')->getPaymentGatewayUrl(); ?>">
    <input type="hidden" name="orderId" value="<?php echo $orderId; ?>">
    <input type="submit" value="<?php echo $this->__('Make Payment') ?>" />
</form>