<div class="form-list" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
	<div class="payment_unipoagos_description" style="padding-bottom: 10px;padding-top: 5px;">
    	<?php // echo Mage::getStoreConfig('payment/wallet_upgrade/description'); ?>
    	<?php echo $this->__('Please enter a valid mobile phone number. Then complete your order below to be redirected to the payment page.'); ?>
	</div>
    <div style="padding-bottom: 10px;">
        <label for="mobileNumber" class="required"><em>*</em><?php echo $this->__('Mobile Number') ?></label>
        <span>
      <input style="height: auto!important;" pattern="[0-9]*"  type="text" title="<?php echo $this->__('Mobile Number') ?>" name="payment[mobile_number]" class="input-text required-entry" id="mobileNumber" value="<?php echo $this->htmlEscape($this->getInfoData('mobile_number')) ?>" />
    </span>
    </div>
</div>
<div>
    <?php echo $this->getMethod()->getConfigData('message');?>
</div>